# Site Settings


theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme


title: ANPL
tagline: Autonomous Navigation and Perception Lab Website
email: anpl.aero@gmail.com
description: >
  Researching, developing, and testing autonomous robots at Technion – Israel Institute of Technology
baseurl: ""
url: "https://anpl-technion.github.io"

twitter_username: ANPL_Technion
github_username:  anpl-technion


permalink: pretty

hide_share_buttons: true
theme_color: '#eeeeee'
fixed_navbar: top
#direction: _site


# paginate: 5
# paginate_path: "/research/page:num"

# Disqus Comments
disqus:
 # Leave shortname blank to disable comments site-wide.
 # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
 # shortname: my_disqus_shortname
 shortname: anpl




# Build settings
# theme: bulma-clean-theme
plugins:
 - jekyll-feed
 - jekyll/scholar
 - jekyll-sitemap
 - jekyll-paginate
 - jekyll-seo-tag
 - kramdown-parser-gfm
 - jekyll-redirect-from




exclude:
 - Gemfile
 - clean-theme.gemspec
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/




ivereload: true


sass:
 style: compressed
 source_dir: _sass


google_analytics: UA-code-here


defaults:
 -
   scope:
     path: ""
     type: "pages"
   values:
     show_sidebar: true
 -
   scope:
     path: ""
     type: "posts"
   values:
     author: "Anpl"
     layout: post
     show_sidebar: true


markdown: kramdown
highlighter: rouge


footer_menu: example_footer_menu

collections:
  research:
    output: true


excerpt_separator: "<!-- more -->"



collections:
  research:
    output: true
    layout: research
    show_sidebar: false
  team:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  student-projects:
    output: true
    show_sidebar: false
    layout: student_project



scholar:
 # style: simple-ieee.csl
 style: _bibliography/ieee.csl 
 source: _bibliography
 bibliography_template: bib #bib_thumbnail
 bibliography: VadimIndelman.bib
 group_by: type
 type_order: [article, InProceedings]
 sort_by: year
 order: descending

# Google Analytics
google_analytics: G-XH2GVJYE1D

categories_order:
  - staff
  - phd_students
  - master_student
  - undergraduate_students
  - visiting_students


default_bib_image: "/img/team/drone_a.jpg"
